### ISSUE TITLE
exception in config running

### ISSUE THREAD

**Issue by willwade** [AceCentre/TranslateAndTTS#26]
```
Traceback (most recent call last):
  File "widget.py", line 934, in <module>
  File "widget.py", line 235, in _init_
IndexError: list index out of range
```

On some peoples installs/running

**Comment by willwade** [comment]
i wonder if someones sapi list could be empty.. is that causing this?


```
			if isinstance(item, list) and len(item) > 0:
				item = self.ui.listWidget_sapi.findItems(item[0], PySide6.QtCore.Qt.MatchExactly)

```

maybe needed at 235
